apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "blue-pool"
spec:
  blocks:
  - cidr: "192.169.2.0/24"
  # - start: "192.169.2.2"
  #   stop: "192.169.2.253"
  serviceSelector:
    matchLabels:
      bgp: blue
  allowFirstLastIPs: "No"