---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secret
  namespace: wordpress
spec:
  encryptedData:
    password: AgCR5mkgH09dqF599vBnXU3FnTCyzKiTxY3WKaYVUp+vY+E1DlAvU7rxGbV0uFtElFX2GXx9/Kd6MihzlG71BDZNUdrjLLo7ciCKf/tn+sCxJh7m/J4UcoWXpsRfJbBEyz4CR2TiYbV3KMRYaO1gvE2mE67gMGku3gF1HBx41cf5V35ljNPrGNoFLHJsZERv0RAw539jxoEo1NIkaiVFJghLgcDCdFjJPBPWvuEvfzzY/e0jsoR8njV7vE+WEWHeqjrGsTIdCWshUt/lERJzMYixCFjIUR9BnM09Hvadu+BLyQTcGSDiM1PSyOKqpc5V+NhRFhKicLx80ZNZs+yOJqdGkGZGZFwVPRnWnFPcL2TR/IcikUHTpTHuG+g0HbERnLVKP6OArzZC2bSxIz5T3qN9zCDLH5sr7Z+uGKjnZa3aZHWDeyly1LFmoayUcqqRIT/THitMdLxjXrhYA47p4Qb2VjAdS0THFS5laKonBK8BwVMAiUzRFkWLUBLna19BBd1m6zuRSRgN0fjtYi32fIrphyCs4YVfWYfwIV1Kbvl5Ewrf7FB6s1mC69zMrA3BKs3ySW8R40QC7RftqGSDZ1IRULMNzpH73ats28XG1cb5xsKKoAu8Zdo42+R9KYi8CTxQ/HEi6uZ2BfY4D2OxuqSsGs91F/FS8HJ38RMr++Y30GpGzJ74EPWbu4jdtmEIQQWsO1pCpoHihuZFS52ht7k=
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-secret
      namespace: wordpress
    type: Opaque
