apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: nextcloud
spec:
  containers:
  - name: debug-container
    image: busybox
    command: [ "sleep", "infinity" ]
    securityContext:
      privileged: true
