apiVersion: v1
kind: Pod
metadata:
  name: tmp-pod
  namespace: firefly
spec:
  containers:
  - name: tmp-container
    image: debian
    command:
      - sleep
      - "3600"
  #   volumeMounts:
  #   - name: mi-volumen
  #     mountPath: /config
  # resources:
  # volumes:
  # - name: mi-volumen
  #   persistentVolumeClaim:
  #     claimName: frigate-config