apiVersion: v1
kind: Pod
metadata:
  name: tmp-pod
  namespace: domotica
spec:
  containers:
  - name: tmp-container
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: mi-volumen
      mountPath: /data
  resources:
  volumes:
  - name: mi-volumen
    persistentVolumeClaim:
      claimName: homeassistant2
