apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ip-updater-mikrotik-wireguard
  namespace: default
spec:
  schedule: "0 */5 * * *" # Esto ejecutará el job cada 5 horas. Ajusta esto según lo necesites.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: updater
            image: juanjocop/update-cloudflare-dns:latest # Reemplaza esto con la imagen de Docker que contenga tu script.
            imagePullPolicy: Always
            env:
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-api-secret
                  key: CF_API_TOKEN
            - name: CF_ZONE_ID
              valueFrom:
                secretKeyRef:
                  name: cloudflare-dns-config-mikrotik-wireguard-secret
                  key: CF_ZONE_ID
            - name: CF_RECORD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudflare-dns-config-mikrotik-wireguard-secret
                  key: CF_RECORD_NAME
            - name: CF_RECORD_TYPE
              valueFrom:
                secretKeyRef:
                  name: cloudflare-dns-config-mikrotik-wireguard-secret
                  key: CF_RECORD_TYPE
          restartPolicy: OnFailure
