apiVersion: v1
kind: Service
metadata:
  labels:
    app: plex
  name: plex-service
  namespace: plex
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.11.4
spec:
  ports:
  - name: "port-tcp-http"
    port: 32400
    protocol: TCP
    targetPort: 32400
  selector:
    app: plex
  sessionAffinity: None
  type: LoadBalancer