apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.11.7
  namespace: microhackaton
spec:
  selector:
    app: web-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
