apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: plex
  labels:
    app: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
      - name: flaresolverr
        image: flaresolverr/flaresolverr:latest
        ports:
          - containerPort: 8191
            protocol: TCP
        env:
        - name: LOG_LEVEL
          value: info
        - name: LOG_HTML
          value: "false"
        - name: CAPTCHA_SOLVER
          value: none
        - name: TZ
          value: Europe/Madrid
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Gi"
            cpu: "0.5"
