apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-service
  namespace: plex  
  labels:
    app: flaresolverr
spec:
  selector:
    app: flaresolverr
  ports:
    - name: api
      port: 8191
      targetPort: 8191
      protocol: TCP
