apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: generic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - image: pihole/pihole:latest
          imagePullPolicy: Always
          name: pihole
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "350Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "3000m"
          env:
            - name: TZ
              value: Europe/Madrid
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-admin-pass
                  key: adminpassword
          volumeMounts:
            - mountPath: /etc/pihole
              subPath: pihole
              name: pihole-claim
            - mountPath: /etc/dnsmasq.d
              subPath: dnsmasq
              name: pihole-claim
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
      volumes:
        - name: pihole-claim
          persistentVolumeClaim:
            claimName: pihole