apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: generic  
  labels:
    app: pihole
    bgp: blue
  annotations:
    # metallb.universe.tf/loadBalancerIPs: 192.168.11.4
spec:
  selector:
    app: pihole
  ports:
    - name: webui
      port: 80
      targetPort: 80
      protocol: TCP
    - name: dns
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dnsudp
      port: 53
      targetPort: 53
      protocol: UDP
  type: LoadBalancer
  loadBalancerIp: 192.169.2.250