apiVersion: v1
kind: ConfigMap
metadata:
  name: otbr-config
  namespace: domotica2
  labels:
    app: otbr
data:
  # TTY virtual que creará el sidecar socat
  OT_RCP_DEVICE: "spinel+hdlc+uart:///tmp/ttyOTBR?uart-baudrate=460800"
  # Interfaz del backbone/IP infra del NODO donde corre el pod (ajústala)
  OT_INFRA_IF: "eth0"
  OT_THREAD_IF: "wpan0"
  OT_LOG_LEVEL: "7"
