apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otbr-data
  namespace: domotica2
  labels:
    app: otbr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
