apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-data
  namespace: domotica2
  labels:
    app: matter-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn