apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    # l2loadbalancer: enable
    bgp: blue
  # annotations:
  #   lbipam.cilium.io/ips: 192.168.11.9
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  # loadBalancerIP: 192.168.11.11