apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
  name: nextcloud-service
  namespace: nextcloud
spec:
  ports:
    - name: http-nextcloud
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30101
  selector:
    app: nextcloud
  sessionAffinity: None
  type: NodePort

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: nextcloud
#   name: nextcloud-service-lb
#   namespace: nextcloud
#   annotations:
#     metallb.universe.tf/loadBalancerIPs: 192.168.11.17
# spec:
#   ports:
#     - name: http-nextcloud
#       port: 80
#       protocol: TCP
#       targetPort: 80
#   selector:
#     app: nextcloud
#   sessionAffinity: None
#   type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb-service
  namespace: nextcloud
spec:
  ports:
    - name: "3306"
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mariadb
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: nextcloud
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: redis