apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
  name: nextcloud-service
  namespace: nextcloud
spec:
  ports:
    - name: http-nextcloud
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nextcloud
  sessionAffinity: None
  type: ClusterIP