apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: nextcloud
spec:
  serviceName: "mariadb"
  replicas: 1
  updateStrategy:
        type: RollingUpdate
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: password
        resources:
          requests:
            memory: "600Mi"
            cpu: "250m"
          limits:
            memory: "800Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
        - name: mariadb-50-cnf
          mountPath: /etc/mysql/mariadb.conf.d/50-server.cnf
          subPath: 50-server.cnf
        livenessProbe:
          exec:
            command: 
            - sh
            - -c
            - "mariadb-admin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command: 
            - sh
            - -c
            - "mariadb-admin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
              - key: node.kubernetes.io/remote
                operator: Exists
      volumes:
      - name: mariadb-50-cnf
        configMap:
          name: 50-server.cnf
  volumeClaimTemplates:
  - metadata:
      name: mariadb-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn" # Asegúrate de que esto coincida con el nombre de tu StorageClass de Longhorn
      resources:
        requests:
          storage: 1Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: nextcloud
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      annotations:
        config.linkerd.io/skip-outbound-ports: "6379"
        config.linkerd.io/skip-inbound-ports: "6379"
    spec:
      containers:
      - name: redis
        image: redis:7.0.14-alpine
        ports:
        - containerPort: 6379
        args: [ "--requirepass", "$(REDIS_PASSWORD)" ]
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        # volumeMounts:
        # - name: redis-config
        #   mountPath: /conf/redis.conf
        #   subPath: redis.conf
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
      # volumes:
      # - name: redis-config
      #   configMap:
      #     name: redis-configmap
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
              - key: node.kubernetes.io/remote
                operator: Exists