apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: domotica
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        volumeMounts:
        - mountPath: /data
          name: config
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:stable
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "1700Mi"
            cpu: "150m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homeassistant2
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"