apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-red
  name: node-red-service
  namespace: domotica
spec:
  ports:
    - name: "1880"
      port: 1880
      protocol: TCP
      targetPort: 1880
  selector:
    app: node-red
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-red
    # l2loadbalancer: enable
    bgp: blue
  name: node-red-service-lb
  namespace: domotica
  annotations:
    # metallb.universe.tf/loadBalancerIPs: 192.168.11.14
    # lbipam.cilium.io/ips: 192.169.88.2
spec:
  ports:
    - name: http-nodered
      port: 1880
      protocol: TCP
      targetPort: 1880
  selector:
    app: node-red
  # sessionAffinity: None
  # loadBalancerIP: 192.168.11.2
  type: LoadBalancer