apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora
  namespace: nextcloud
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: collabora
  template:
    metadata:
      labels:
        app: collabora
    spec:
      containers:
      - name: collabora
        image: collabora/code:latest
        ports:
        - containerPort: 9980
        resources:
          limits:
              cpu: "300m"
              memory: "512i"
          requests:
              cpu: "100m"
              memory: "256Mi"
        envFrom:
        - secretRef:
            name: collabora-secret 
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
              - key: node.kubernetes.io/performance
                operator: In
                values:
                - "high"
