# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: collabora-ingress
#   namespace: nextcloud
#   labels:
#     app: nextcloud
#   annotations:
#     ingress.cilium.io/service-type: NodePort
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
#     ingress.cilium.io/insecure-node-port: 30100
#     ingress.cilium.io/secure-node-port: 30101
#     ingress.cilium.io/websocket: enabled
# spec:
#   ingressClassName: cilium
#   tls:
#    - hosts:
#        - collabora.liontechsolution.com
#      secretName: tls-collabora-ingress-http
#   rules:
#   - host: collabora.liontechsolution.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: collabora-service
#             port:
#               number: 9980