apiVersion: v1
kind: Service
metadata:
  labels:
    app: collabora
  name: collabora-service
  namespace: nextcloud
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.11.23
spec:
  ports:
    - port: 9980
      protocol: TCP
      targetPort: 9980
  selector:
    app: collabora
  sessionAffinity: None
  type: LoadBalancer