# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: wordpress-ceres-ingress
#   namespace: wordpress
#   annotations:
#     kubernetes.io/ingress.class: "traefik"
#     # traefik.ingress.kubernetes.io/rewrite-target: /
#     # traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
# spec:
#   tls:
#    - hosts:
#        - ceresterapiayformacion.com
#      secretName: tls-ceres-ingress-http
#   rules:
#   - host: ceresterapiayformacion.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: wordpress-ceres-service
#             port:
#               number: 80

# ---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-maitri-ingress
  namespace: wordpress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # traefik.ingress.kubernetes.io/rewrite-target: /
    # traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
   - hosts:
       - asociacionmaitri.es
     secretName: tls-maitri-ingress-http
  rules:
  - host: asociacionmaitri.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress-maitri-service
            port:
              number: 80