apiVersion: v1
kind: Service
metadata:
  labels:
    app: home-assistant
  name: home-assistant
  namespace: domotica2
spec:
  ports:
    - name: "http"
      port: 8123
      protocol: TCP
      targetPort: 8123
  selector:
    app: home-assistant
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: home-assistant
    bgp: blue
  name: home-assistant-loadbalancer
  namespace: domotica2
spec:
  ports:
    - name: coiot
      port: 5683
      protocol: UDP
      targetPort: 5683
    - name: http
      port: 8123
      protocol: TCP
      targetPort: 8123
  selector:
    app: home-assistant
  sessionAffinity: None
  loadBalancerIP: 192.169.2.7
  type: LoadBalancer