apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
  namespace: monitoring
  labels:
    # l2loadbalancer: enable
    bgp: blue
  # annotations:
  #   lbipam.cilium.io/ips: 192.168.11.8
spec:
  selector:
    prometheus: prometheus-persistant
  type: LoadBalancer
  ports:
    - name: web
      protocol: TCP
      port: 9090
      targetPort: web
  # loadBalancerIP: 192.168.11.8