apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-persistant
  namespace: monitoring
spec:
  replicas: 1
  retention: 7d
  resources:
    requests:
      memory: 2500Mi
      cpu: "700m"
    limits:
      memory: 5Gi
      cpu: "1500m"
  nodeSelector:
    node.kubernetes.io/local: "true"
    node-role.kubernetes.io/worker: "true"
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - longhorn-prometheus-servicemonitor
      - kube-state-metrics
      - node-exporter
      - kubelet
  podMonitorSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - linkerd-controller
      - linkerd-proxy
      - linkerd-service-mirror
  serviceMonitorNamespaceSelector: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: In
            values:
            - "true"
          - key: node.kubernetes.io/local
            operator: Exists
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 40Gi