apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate-server
  labels:
    app: frigate
  namespace: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      containers:
      - name: frigate
        image: ghcr.io/blakeblackshear/frigate:stable
        ports:
        - name: frigate
          containerPort: 5000
        - name: rtmp
          containerPort: 1935
        volumeMounts:
        - name: frigate-config
          mountPath: /config
          readOnly: true
        - name: frigate-media
          mountPath: /media/frigate
        resources:
            requests:
              memory: "800Mi"
              cpu: "700m"
            limits:
              memory: "1700Mi"
              cpu: "1300m"
        envFrom:
          - secretRef:
              name: frigate-password
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
              - key: node.kubernetes.io/performance
                operator: In
                values:
                - "high"
      volumes:
      - name: frigate-media
        persistentVolumeClaim:
          claimName: frigate-media
      - name: frigate-config
        secret:
          secretName: frigate-config
