apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate-server
  labels:
    app: frigate
  namespace: domotica
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      # initContainers:
      # - name: volume-permissions
      #   image: busybox
      #   command: ["sh", "-c", "chown -R 1000:1000 /media"]
      #   volumeMounts:
      #   - mountPath: /media
      #     name: frigate-media
      containers:
      - name: frigate
        image: ghcr.io/blakeblackshear/frigate:stable
        imagePullPolicy: Always
        ports:
        - name: frigate
          containerPort: 5000
        - name: rtmp
          containerPort: 1935
        - name: rtsp
          containerPort: 8554
        volumeMounts:
        - name: frigate-config
          mountPath: /config
        # - name: frigate-secret
        #   mountPath: /config/config.yaml
        #   subPath: config.yaml
        #   readOnly: true
        - name: frigate-media
          mountPath: /media/frigate
        - name: usb
          mountPath: /dev/bus/usb
        resources:
            requests:
              memory: "2000Mi"
              cpu: 750m
            limits:
              memory: "4Gi"
              cpu: 3
        envFrom:
          - secretRef:
              name: frigate-password
        securityContext:
          privileged: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
              - key: node.kubernetes.io/performance
                operator: In
                values:
                - "high"
      volumes:
      - name: frigate-media
        persistentVolumeClaim:
          claimName: frigate-media
      # - name: frigate-secret
      #   secret:
      #     secretName: frigate-config
      - name: frigate-config
        persistentVolumeClaim:
          claimName: frigate-config
      - name: usb
        hostPath:
          path: /dev/bus/usb