---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-password
  namespace: domotica
spec:
  encryptedData:
    FRIGATE_RTSP_PASSWORD: AgBkvjCYca+3GjY4xD/b9oYioe+2Bhl5UO/WBwFuTmJlOzL662tSdtayTNZrsGLmreCzI4FAfRLjza4hSILKBKjO+j1HwvRGxvK0kvpllYWX5biI6oD3wMRQXipbuoN9GDk5DqUcMN3weKc4VddxfjFeO/8CNCNhyXYBJBcN4HfqhgugaEAYyRPPyFbi4Evwk/av1+DxsQQpq3KrncJ18y2YKdJ0vjKpMTHpLeF8auqh69dMUA+udPYg1643aac7NI/PP3FFwDX2vh9ooo3QHL+6nzx4OvNfuziIP0+u9ynohSNBq6+3TNVy30PS2UCKTPkRs0GUs+QQBt490is7NdzTJkOtGJy73DZ8Y362w79Q2MfKmPxw7NYXQ5BWHjRT4pNCIr/R37P8csekL3yks9QtjVDH1JFN1HJfyKaRBSiDUNMY0pN2Tlv95dSJnH5ip+9APZmfghxv1abZHX22wDJ/3wUMvFdx34fp1OPoVnQNpUNsx9XRCB614NxSQroF/fxyn99EkmKWfZJlN27XZoXdcYsg06PweMi5MQ27Q1tUv2ahcwpLMfgnByqKIN9NRVg3uCbIg0PKKRKbu1fi0A4rOTlC7qM1Q007gHaH7TNXAwKkMw8Rhb4nTz30GgAf266qknWIBgXqVEQzCHuXGHz6FgRAcG/dKCqe5/OH6d49wmHHORqc/GzZtkcKJeuGoz7Hde5pT9QGftxL3dSCWFY=
  template:
    metadata:
      creationTimestamp: null
      name: frigate-password
      namespace: domotica
    type: Opaque
