apiVersion: v1
kind: Service
metadata:
  name: frigate-service
  namespace: domotica  
  labels:
    app: frigate
    bgp: blue
spec:
  selector:
    app: frigate
  ports:
    - name: frigate
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: frigate-rtmp
      port: 1935
      targetPort: 1935
      protocol: TCP
    - name: frigate-rtsp
      port: 8554
      targetPort: 8554
  type: LoadBalancer
  loadBalancerIP: 192.169.2.8