apiVersion: v1
kind: Service
metadata:
  name: frigate-service
  namespace: domotica  
  labels:
    app: frigate
    bgp: blue
    # l2loadbalancer: enable
  annotations:
    #metallb.universe.tf/loadBalancerIPs: 192.168.11.235
    # lbipam.cilium.io/ips: 192.168.11.235
spec:
  selector:
    app: frigate
  ports:
    - name: frigate
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: frigate-rtmp
      port: 1935
      targetPort: 1935
      protocol: TCP
  type: LoadBalancer