apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: plex  
  labels:
    app: sonarr
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.11.3
spec:
  selector:
    app: sonarr
  ports:
    - name: webui
      port: 80
      targetPort: 8989
      protocol: TCP
  type: LoadBalancer
