apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: domotica2
  labels:
    app: mosquitto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0.18
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 9001
          name: websockets
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mosquitto_pub -h localhost -p 1883 -t '$SYS/broker/ping' -m 'ping' -q 0 || exit 1"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 3
          periodSeconds: 5
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      restartPolicy: Always
      nodeSelector:
        node.kubernetes.io/performance: high
        node-role.kubernetes.io/worker: "true"
