apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service-lb
  namespace: domotica2
  labels:
    app: mosquitto
    bgp: blue
spec:
  type: LoadBalancer
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    protocol: TCP
  - name: websockets
    port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    app: mosquitto
  loadBalancerIP: 192.169.2.13

---

apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: domotica2
  labels:
    app: mosquitto
spec:
  type: ClusterIP
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    protocol: TCP
  - name: websockets
    port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    app: mosquitto