apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: domotica2
data:
  mosquitto.conf: |
    # Mosquitto configuration file
    
    # General settings
    log_dest stdout
    log_type error
    log_type warning
    log_type notice
    log_type information
    connection_messages true
    log_timestamp true
    
    # Default listener
    listener 1883
    protocol mqtt
    
    # WebSocket listener
    listener 9001
    protocol websockets
    
    # Allow anonymous connections (change to false for production)
    allow_anonymous true
    
    # Uncomment and configure for authentication
    # password_file /mosquitto/config/passwd
    # acl_file /mosquitto/config/acl
