apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt-service
  namespace: domotica2
  labels:
    app: zigbee2mqtt
spec:
  type: LoadBalancer
  ports:
  - name: frontend
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: zigbee2mqtt
  loadBalancerIP: 192.169.2.14
