apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-config
  namespace: domotica2
data:
  configuration.yaml: |
    homeassistant: true
    permit_join: false

    frontend:
      port: 8080

    mqtt:
      server: mqtt://192.169.2.13:1883

    serial:
      # Ubicación del SLZB-MR3 por TCP
      port: tcp://192.168.50.18:7638
      adapter: zstack
      # baudrate: 115200   # (opcional; ignorado en TCP)
      disable_led: false

    advanced:
      transmit_power: 20   # dBm (ver nota abajo)
      channel: 20
      log_level: info
       