apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: domotica2
  labels:
    app: zigbee2mqtt
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:1.33.2
        ports:
        - containerPort: 8080
          name: frontend
        env:
        - name: TZ
          value: "Europe/Madrid"
        - name: ZIGBEE2MQTT_DATA
          value: "/app/data"
        volumeMounts:
        - name: zigbee2mqtt-data
          mountPath: /app/data
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      - name: config-helper
        image: busybox:1.36
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 3600; done"]
        volumeMounts:
        - name: zigbee2mqtt-data
          mountPath: /app/data
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: zigbee2mqtt-data
        persistentVolumeClaim:
          claimName: zigbee2mqtt-pvc
      restartPolicy: Always
      nodeSelector:
        node.kubernetes.io/performance: high
        node-role.kubernetes.io/worker: "true"
