apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-server
  labels:
    app: wireguard
  namespace: wireguard
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard
        image: linuxserver/wireguard
        ports:
        - name: wireguard
          containerPort: 51820
          protocol: UDP
        volumeMounts:
        - name: wireguard-config
          mountPath: /config
          # readOnly: true
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_MODULE"]
        resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
        envFrom:
          - configMapRef:
              name: wireguard-configmap
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
      volumes:
      - name: wireguard-config
        persistentVolumeClaim:
          claimName: wireguard-config
