apiVersion: v1
kind: Service
metadata:
  name: wireguard-service
  namespace: wireguard  
  labels:
    app: wireguard
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.11.13
spec:
  selector:
    app: wireguard
  ports:
    - name: dnsudp
      port: 51820
      targetPort: 51820
      protocol: UDP
  type: LoadBalancer