apiVersion: v1
kind: Service
metadata:
  name: bitcoin-core-service
  namespace: bitcoin
spec:
  selector:
    app: bitcoin-core  # Asegúrate de que esto coincida con las etiquetas de tu StatefulSet/Deployment de Bitcoin
  ports:
    - protocol: TCP
      port: 8333
      targetPort: 8333
  type: ClusterIP
