apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # La URL de staging de Let's Encrypt
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: juanjocop@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: cilium

---


apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-dns
spec:
  acme:
    # La URL de staging de Let's Encrypt
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: juanjocop@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
          email: juanjocop@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-secret
            key: CF_API_TOKEN