---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: nextcloud
spec:
  encryptedData:
    redis-password: AgBTOtTD94gURSsvYk+3mcupW8CdIHaWHrFqdZILbvmdfzI2nnv7g5ojqt2Dsgywh/1MA48eXLkU7F/XNftPstVCpwEv7Fo2dOW0nNruEhLAJ9PLzRLzhkZvOeL6L1Pb9YUF+v+LbsW0kXFm+RZ73/nXQKdaKeB/FjMQzZzwsWJNG0g7P8BetJ6O+dkMwEE7Y+NYq0hWiy8GQ/v2SWtCjmJRloIJGvjtpmwBma4Cp/BEa6jPLZjndicXg39ZME4fHYvqR9vPm4aLb/h9CzFa2rtDlgY5xC++kVXj5q4A39kTaNFXNj5tAlZ568MX2qg5BgVOImnt1F7YKH1GQKdw/QZeDZHhp1qwWjtEILXd6pQyO4InE2caiq5bMwtVl96h2Qq/8i3AuacadkyK3C5e8wDINQYLNGNVUnPrqLq5wL4n0ImM9I4lxTj0h5ifOPELeZos3yPJt4KPw7+X9hjP8nTlI+zw/O8GQzgLhK7SH+tHABS4K+2+DEVRjrNGpLrc8ki/MAeyKIalRombTia/8g+zeufmBlOJ52vpcRyt4jndLhG0YeJ4RCY4Q8rp683QfRQlqvXUIL0ftPDrw6AdIXcyxZ/Uh8jUodSrDCUfd9woDKF1hz3wZrjBIPIl7IKDEa3n6kXLjNQrcAv342Z6FQWR3kzdJ53hTSTiNJOf6GI8VMDRYV4Ai5xMOV9WLB1ghew/PLzq8mG/t/85jiM3zjA0
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: nextcloud
    type: Opaque
